### ISSUE TITLE
Set up percentiles-histogram for metrics in all Spring Boot apps

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health-spring-boot-demo#211]
Something like that
```yaml
management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 50ms
      maximum-expected-value:
        http.server.requests: 5s
      slo:
        http.server.requests: 2s
```
See https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/PercentileHistogramBuckets.java
